# Generated by Django 3.0.5 on 2020-04-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='pesel_lub_nip_wierzyciela',
            field=models.CharField(default=3, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='adres_dluznika',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='adres_dluznika_cd',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='adres_wierzyciela',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='adres_wierzyciela_cd',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='email_dluznika',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='email_wierzyciela',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='nazwa_dluznika',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='nazwa_dluznika_cd',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='nazwa_wierzyciela',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='nazwa_wierzyciela_cd',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='numer_konta',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='plik',
            field=models.FileField(upload_to='Files'),
        ),
    ]
